let str = "hello,WORLD,javascript";
console.log(str.length);
console.log(str.charAt(4));
console.log(str.indexOf("l"));
console.log(str.lastIndexOf("l"));
console.log(str.slice(7, 11));
console.log(str.toLocaleLowerCase());
console.log(str.toUpperCase());
console.log(str.split(" "));
console.log(["a", "b"].join("-"));
